# In application.yml
spring:
  ai:
    deepseek:
      api-key: ***
    ollama:
      chat:
        model: deepseek-r1:8b
      embedding:
        enabled: false
    dashscope:
      api-key: ***
      embedding:
        enabled: true
        options:
          model: text-embedding-v4

    vectorstore:
      qdrant:
        host: localhost
        port: 6334

        collection-name: vector-message

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_ai_use?allowPublicKeyRetrieval=true&useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: liao951126